# dataset
dataset_name: myo
dataset_path: ../dataset/MyoDataset
subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
sessions: [1, 2]
trials: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
gestures: [1, 2, 3, 4, 5, 6, 7, 8, 9]
num_channels: 8

train_trials: [1, 3, 5, 7, 9]
test_trials: [2, 4, 6, 8, 10]
window_size: 52
window_step: 5


# preprocess
amplify: False
lpf: False
bpf: False
u_normalization: False
u: 256
abs: False
move_average: False


# train
need_pretrain: False
num_epochs: 100
batch_size: 32
optimizer: Adam
base_lr: 0.01
weight_decay: 0.0001
milestones: [5, 10, 25]
gamma: 0.1


# model
model_path: model

# logger
log_path: log

# tensorboard
tb_path: runs


